### ISSUE TITLE
get working on Ubuntu xenial out of the box

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-cpp#46]

**Comment by frobware** [comment]
Is poco-1.7.7 a hard requirement? Most of the other dependencies we can get through apt.

**Comment by yasserf** [comment]
Which version is available through apt? I don't have a preference as long it works

**Comment by frobware** [comment]
On xenial we get:

```
$ apt-cache madison libpoco-dev
libpoco-dev | 1.3.6p1-5.1build1 | http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
      poco | 1.3.6p1-5.1build1 | http://gb.archive.ubuntu.com/ubuntu xenial/universe Sources
```

When I first tried to compile the tree a few days ago I naively just installed this version but the build failed. I can spend a little time to see if this is just files have since been renamed and that the API that we require is available through the packaged version. If it is, I would say use the packaged version as it simplifies builds (for us) and other clients.

**Comment by yasserf** [comment]
I would suggest we first see if POCO supports ssl out of the box

https://github.com/deepstreamIO/deepstream.io-client-cpp/issues/57

If not, it probably will be dropped in the near future with something that does. As far as I'm aware uWS does
